# Site settings
title: Funz
email: yann.richet@irsn.fr
description: Funz project website.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: https://Funz.github.io/ # the base hostname & protocol for your site
git_address: https://github.com/Funz/funz.github.io
git_edit_address: https://github.com/Funz/funz.github.io/edit/master/

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Paris
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _demos
    type: demos
  values:
    layout: demos
    sectionid: demos
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  demos:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
